# == Global project settings ===========================================

name:             toner-background
description:      ''
attribution:      'Map Data © OpenStreetMap'
bounds:           [-123.640, 36.791, -121.025, 38.719]
center:           [-122.5369, 37.8704, 13]
format:           png
interactivity:    false
minzoom:          0
maxzoom:          20
srs:              '+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over'
metatile:         1


# == Layer & Datasource defaults =======================================

_layer_default:   &layer
  'srs-name':     '3857'
  srs:            '+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over'

_pg_default:      &postgis
  type:           postgis
  dbname:         '{{dbname}}'
  host:           '{{dbhost}}'
  user:           '{{dbuser}}'
  password:       '{{dbpassword}}'
  port:           '{{dbport}}'
  geometry_field: way
  srid:           3857
  extent:         '-20037508.34,-20037508.34,20037508.34,20037508.34'
  srs:            '+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over'

_shp_default:     &shapefile
  type:           shape
  estimate_extent: false
  extent:         '-20037508.34,-20037508.34,20037508.34,20037508.34'
  srs:            '+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over'


# == Stylesheets =======================================================

Stylesheet:
  - map.mss


# == Layers ============================================================

Layer:

  - <<: *layer
    name: land-shapes-110m
    id:   land-shapes-110m
    class: shore
    properties:
      maxzoom: 1
    Datasource:
      <<: *shapefile
      file: shp/natural_earth/ne_110m_land-merc.zip

  - <<: *layer
    name: country-shapes-110m
    id:   country-shapes-110m
    class: shore
    properties:
      minzoom: 2
      maxzoom: 2
    Datasource:
      <<: *shapefile
      file: shp/natural_earth/ne_110m_admin_0_countries_lakes-merc.zip

  - <<: *layer
    name: country-shapes-50m
    id:   country-shapes-50m
    class: shore
    properties:
      minzoom: 3
      maxzoom: 5
    Datasource:
      <<: *shapefile
      file: shp/natural_earth/ne_50m_admin_0_countries_lakes-merc.zip

  - <<: *layer
    name: country-shapes-10m
    id:   country-shapes-10m
    class: shore
    properties:
      minzoom: 6
      maxzoom: 7
    Datasource:
      <<: *shapefile
      file: shp/natural_earth/ne_10m_admin_0_countries_lakes-merc.zip

  - <<: *layer
    name: coastline-10m
    id:   coastline-10m
    class: shore
    Datasource:
      <<: *shapefile
      file: shp/natural_earth/ne_10m_coastline-merc.zip

  - <<: *layer
    name: land
    id:   land
    properties:
      minzoom: 8
    Datasource:
      <<: *shapefile
      file: shp/land-polygons-split-3857/land_polygons.shp

  - <<: *layer
    name: admin1-lines-50m
    id:   admin1-lines-50m
    properties:
      minzoom: 3
      maxzoom: 5
    Datasource:
      <<: *shapefile
      file: shp/natural_earth/ne_50m_admin_1_states_provinces_lines_shp-merc.zip

  - <<: *layer
    name: admin1-lines-10m
    id:   admin1-lines-10m
    properties:
      minzoom: 6
      maxzoom: 9
    Datasource:
      <<: *shapefile
      file: shp/natural_earth/ne_10m_admin_1_states_provinces_lines_shp-merc.zip

  - <<: *layer
    name: ne_10m_admin_0_boundary_lines_land
    id:   ne_10m_admin_0_boundary_lines_land
    class: country-boundary-10m
    properties:
      minzoom: 6
      maxzoom: 9
      cache-features: on
    Datasource:
      <<: *shapefile
      file: shp/natural_earth/ne_10m_admin_0_boundary_lines_land-merc.zip

  - <<: *layer
    name: admin1-lines-osm
    id:   admin1-lines-osm
    properties:
      minzoom: 10
    Datasource:
      <<: *postgis
      geometry_field: geometry
      table: >
        (
          SELECT
            geometry,
            name
          FROM osm_admin
          WHERE geometry && !bbox!
            AND type = 'administrative'
            AND admin_level = 4
        ) AS _

  - <<: *layer
    name: green-areas-high
    id:   green-areas-high
    properties:
      minzoom: 14
    Datasource:
      <<: *postgis
      geometry_field: geometry
      table: >
        (
          SELECT
            name,
            type,
            geometry,
            area
          FROM osm_green_areas
          WHERE geometry && !bbox!
        ) AS _

  - <<: *layer
    name: green-areas-med
    id:   green-areas-med
    properties:
      minzoom: 11
      maxzoom: 13
    Datasource:
      <<: *postgis
      geometry_field: geometry
      table: >
        (
          SELECT
            name,
            type,
            geometry,
            area
          FROM osm_green_areas_z13
          WHERE geometry && !bbox!
        ) AS _

  - <<: *layer
    name: green-areas-low
    id:   green-areas-low
    properties:
      minzoom: 10
      maxzoom: 10
    Datasource:
      <<: *postgis
      geometry_field: geometry
      table: >
        (
          SELECT
            name,
            type,
            geometry,
            area
          FROM osm_green_areas_z10
          WHERE geometry && !bbox!
        ) AS _

  - <<: *layer
    name: water-bodies-high
    id:   water-bodies-high
    properties:
      minzoom: 14
    Datasource:
      <<: *postgis
      geometry_field: geometry
      table: >
        (
          SELECT
            name,
            type,
            geometry,
            area
          FROM osm_water_areas
          WHERE geometry && !bbox!
        ) AS _

  - <<: *layer
    name: water-bodies-med
    id:   water-bodies-med
    properties:
      minzoom: 11
      maxzoom: 13
    Datasource:
      <<: *postgis
      geometry_field: geometry
      table: >
        (
          SELECT
            name,
            type,
            geometry,
            area
          FROM osm_water_areas_z13
          WHERE geometry && !bbox!
        ) AS _

  - <<: *layer
    name: water-bodies-low
    id:   water-bodies-low
    properties:
      minzoom: 8
      maxzoom: 10
    Datasource:
      <<: *postgis
      geometry_field: geometry
      table: >
        (
          SELECT
            name,
            type,
            geometry,
            area
          FROM osm_water_areas_z10
          WHERE geometry && !bbox!
        ) AS _

  - <<: *layer
    name: lakes-110m
    id:   lakes-110m
    class: shore
    properties:
      maxzoom: 2
    Datasource:
      <<: *shapefile
      file: shp/natural_earth/ne_110m_lakes-merc.zip

  - <<: *layer
    name: lakes-50m
    id:   lakes-50m
    class: shore
    properties:
      minzoom: 3
      maxzoom: 6
    Datasource:
      <<: *shapefile
      file: shp/natural_earth/ne_50m_lakes-merc.zip

  - <<: *layer
    name: lakes-10m
    id:   lakes-10m
    class: shore lakes
    properties:
      minzoom: 7
      maxzoom: 7
    Datasource:
      <<: *shapefile
      file: shp/natural_earth/ne_10m_lakes-merc.zip

  - <<: *layer
    name: ne-roads
    id:   ne-roads
    properties:
      minzoom: 6
      maxzoom: 8
    Datasource:
      cache-features: on
      <<: *shapefile
      file: shp/natural_earth/ne_10m_roads-merc.zip

  - <<: *layer
    name: roads
    id:   roads
    class: roads
    properties:
      minzoom: 9
      cache-features: on
    Datasource:
      <<: *postgis
      geometry_field: geometry
      table: >
        (
          SELECT *
          FROM high_road(!scale_denominator!, !bbox!)
        ) AS _

  - <<: *layer
    name: buildings-high
    id:   buildings-high
    properties:
      minzoom: 14
    Datasource:
      <<: *postgis
      geometry_field: geometry
      table: >
        (
          SELECT
            osm_id,
            name,
            type,
            geometry,
            area
          FROM osm_buildings
          WHERE geometry && !bbox!
        ) AS _

  - <<: *layer
    name: buildings-med
    id:   buildings-med
    properties:
      minzoom: 13
      maxzoom: 13
    Datasource:
      <<: *postgis
      geometry_field: geometry
      table: >
        (
          SELECT
            name,
            type,
            geometry,
            area
          FROM osm_buildings_z13
          WHERE geometry && !bbox!
        ) AS _
